#!/bin/sh

PIP="/var/packages/python/target/bin/pip"
PYTHON="/var/packages/python/target/bin/python"

${PIP} install --upgrade pip > '/tmp/TSW2.log'
cd "${SYNOPKG_PKGDEST}" && ${PYTHON} utils/execute_color.py "Installing JSAG3" ${PYTHON} utils/pkg_manager.py "install" "JSAG3" >> '/tmp/TSW2.log'  2>&1
${PIP} install -r requirements.txt >> '/tmp/TSW2.log' 2>&1 
